### ISSUE TITLE
Types broken in v3.39

### ISSUE THREAD

**Issue by IGx89** [fastly/js-compute-runtime#1296]
I'm attempting to update from v3.38.4 to v3.39.0 and am getting lots of type errors:
```
Error: src/index.js(3,21): error TS2307: Cannot find module 'fastly:env' or its corresponding type declarations.
Error: src/index.js(4,37): error TS2307: Cannot find module 'fastly:html-rewriter' or its corresponding type declarations.
Error: src/index.js(27,1): error TS2304: Cannot find name 'addEventListener'.
Error: src/index.js(30,12): error TS2304: Cannot find name 'FetchEvent'.
Error: src/index.js(31,22): error TS2304: Cannot find name 'Response'.
Error: src/index.js(37,22): error TS2304: Cannot find name 'URL'.
```

I have the following at the top of my index.js: `/// <reference types="@fastly/js-compute" />`. When I go to its definition however it shows dist/index.d.ts with the following contents:
```js
export {};
```
The types are gone!

Appears to be caused by #1269

**Comment by case-fastly** [comment]
👋  @IGx89 thanks for letting us know about this, we'll get it addressed asap.

In the meantime, could you try pointing your type reference directly at the `types/index.d.ts` file?

cc @zkat (from our team)

**Comment by harmony7** [comment]
We've put in #1298, which restores the previous behavior for now, and is planned for inclusion into the next release.
